name: DFS Consulting
favicon: null
layout_spectrum: 0.022229389054700732
typography_spectrum: 0.7064941062126309
title: DFS Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3c3c3c'
    - '#8eca49'
    - '#3fa1ca'
    - '#000000'
  brandStrength: 1
  lightness: 0.04713958711363375
  saturation: 0.07406501448713243
  rhythmicContrast: 0.25
purpose: []
